// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfcicjxrvsxkrmktrveb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmY2ljanhydnN4a3Jta3RydmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDM4MDQsImV4cCI6MjA3MzExOTgwNH0.DyjAzDNwgt_w5SQJQDGIP75P9XOL3uC9-WkNvgAAIIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});